Opcodes = {
    0x00: {"command": "BRK", "length": 0, "m": False, "x": False, "mode": "_"},
    0x01: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x02: {
        "command": "COP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x03: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0x04: {
        "command": "TSB",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x05: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x06: {
        "command": "ASL",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x07: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0x08: {"command": "PHP", "length": 0, "m": False, "x": False, "mode": "_"},
    0x09: {
        "command": "ORA",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0x0A: {"command": "ASL", "length": 0, "m": False, "x": False, "mode": "_"},
    0x0B: {"command": "PHD", "length": 0, "m": False, "x": False, "mode": "_"},
    0x0C: {
        "command": "TSB",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x0D: {
        "command": "ORA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x0E: {
        "command": "ASL",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x0F: {
        "command": "ORA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x10: {
        "command": "BPL",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x11: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0x12: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x13: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0x14: {
        "command": "TRB",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x15: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x16: {
        "command": "ASL",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x17: {
        "command": "ORA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0x18: {"command": "CLC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x19: {
        "command": "ORA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x1A: {"command": "INC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x1B: {"command": "TCS", "length": 0, "m": False, "x": False, "mode": "_"},
    0x1C: {
        "command": "TRB",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x1D: {
        "command": "ORA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x1E: {
        "command": "ASL",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x1F: {
        "command": "ORA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x20: {
        "command": "JSR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x21: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x22: {
        "command": "JSL",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x23: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0x24: {
        "command": "BIT",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x25: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x26: {
        "command": "ROL",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x27: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0x28: {"command": "PLP", "length": 0, "m": False, "x": False, "mode": "_"},
    0x29: {
        "command": "AND",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0x2A: {"command": "ROL", "length": 0, "m": False, "x": False, "mode": "_"},
    0x2B: {"command": "PLD", "length": 0, "m": False, "x": False, "mode": "_"},
    0x2C: {
        "command": "BIT",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x2D: {
        "command": "AND",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x2E: {
        "command": "ROL",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x2F: {
        "command": "AND",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x30: {
        "command": "BMI",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x31: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0x32: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x33: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0x34: {
        "command": "BIT",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x35: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x36: {
        "command": "ROL",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x37: {
        "command": "AND",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0x38: {"command": "SEC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x39: {
        "command": "AND",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x3A: {"command": "DEC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x3B: {"command": "TSC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x3C: {
        "command": "BIT",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x3D: {
        "command": "AND",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x3E: {
        "command": "ROL",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x3F: {
        "command": "AND",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x40: {"command": "RTI", "length": 0, "m": False, "x": False, "mode": "_"},
    0x41: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x42: {
        "command": "WDM",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x43: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0x44: {
        "command": "MVP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,$_",
    },
    0x45: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x46: {
        "command": "LSR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x47: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0x48: {"command": "PHA", "length": 0, "m": False, "x": False, "mode": "_"},
    0x49: {
        "command": "EOR",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0x4A: {"command": "LSR", "length": 0, "m": False, "x": False, "mode": "_"},
    0x4B: {"command": "PHK", "length": 0, "m": False, "x": False, "mode": "_"},
    0x4C: {
        "command": "JMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x4D: {
        "command": "EOR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x4E: {
        "command": "LSR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x4F: {
        "command": "EOR",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x50: {
        "command": "BVC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x51: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0x52: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x53: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0x54: {
        "command": "MVN",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,$@2",
    },
    0x55: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x56: {
        "command": "LSR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x57: {
        "command": "EOR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0x58: {"command": "CLI", "length": 0, "m": False, "x": False, "mode": "_"},
    0x59: {
        "command": "EOR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x5A: {"command": "PHY", "length": 0, "m": False, "x": False, "mode": "_"},
    0x5B: {"command": "TCD", "length": 0, "m": False, "x": False, "mode": "_"},
    0x5C: {
        "command": "JMP",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x5D: {
        "command": "EOR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x5E: {
        "command": "LSR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x5F: {
        "command": "EOR",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x60: {"command": "RTS", "length": 0, "m": False, "x": False, "mode": "_"},
    0x61: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x62: {
        "command": "PER",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x63: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0x64: {
        "command": "STZ",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x65: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x66: {"command": "ROR", "length": 0, "m": False, "x": False, "mode": "_"},
    0x67: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0x68: {"command": "PLA", "length": 0, "m": False, "x": False, "mode": "_"},
    0x69: {
        "command": "ADC",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0x6A: {"command": "ROR", "length": 0, "m": False, "x": False, "mode": "_"},
    0x6B: {"command": "RTL", "length": 0, "m": False, "x": False, "mode": "_"},
    0x6C: {
        "command": "JMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x6D: {
        "command": "ADC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x6E: {
        "command": "ROR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x6F: {
        "command": "ADC",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x70: {
        "command": "BVS",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x71: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0x72: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x73: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0x74: {
        "command": "STZ",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x75: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x76: {
        "command": "ROR",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x77: {
        "command": "ADC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0x78: {"command": "SEI", "length": 0, "m": False, "x": False, "mode": "_"},
    0x79: {
        "command": "ADC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x7A: {"command": "PLY", "length": 0, "m": False, "x": False, "mode": "_"},
    0x7B: {"command": "TDC", "length": 0, "m": False, "x": False, "mode": "_"},
    0x7C: {
        "command": "JMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x7D: {
        "command": "ADC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x7E: {
        "command": "ROR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x7F: {
        "command": "ADC",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x80: {
        "command": "BRA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x81: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0x82: {
        "command": "BRL",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x83: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0x84: {
        "command": "STY",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x85: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x86: {
        "command": "STX",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x87: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0x88: {"command": "DEY", "length": 0, "m": False, "x": False, "mode": "_"},
    0x89: {
        "command": "BIT",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0x8A: {"command": "TXA", "length": 0, "m": False, "x": False, "mode": "_"},
    0x8B: {"command": "PHB", "length": 0, "m": False, "x": False, "mode": "_"},
    0x8C: {
        "command": "STY",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x8D: {
        "command": "STA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x8E: {
        "command": "STX",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x8F: {
        "command": "STA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x90: {
        "command": "BCC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0x91: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0x92: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0x93: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0x94: {
        "command": "STY",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x95: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x96: {
        "command": "STX",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x97: {
        "command": "STA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0x98: {"command": "TYA", "length": 0, "m": False, "x": False, "mode": "_"},
    0x99: {
        "command": "STA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0x9A: {"command": "TXS", "length": 0, "m": False, "x": False, "mode": "_"},
    0x9B: {"command": "TXY", "length": 0, "m": False, "x": False, "mode": "_"},
    0x9C: {
        "command": "STZ",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0x9D: {
        "command": "STA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x9E: {
        "command": "STZ",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0x9F: {
        "command": "STA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xA0: {
        "command": "LDY",
        "length": 2,
        "m": False,
        "x": True,
        "mode": "#$_",
    },
    0xA1: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0xA2: {
        "command": "LDX",
        "length": 2,
        "m": False,
        "x": True,
        "mode": "#$_",
    },
    0xA3: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0xA4: {
        "command": "LDY",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xA5: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xA6: {
        "command": "LDX",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xA7: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0xA8: {"command": "TAY", "length": 0, "m": False, "x": False, "mode": "_"},
    0xA9: {
        "command": "LDA",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0xAA: {"command": "TAX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xAB: {"command": "PLB", "length": 0, "m": False, "x": False, "mode": "_"},
    0xAC: {
        "command": "LDY",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xAD: {
        "command": "LDA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xAE: {
        "command": "LDX",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xAF: {
        "command": "LDA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xB0: {
        "command": "BCS",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xB1: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0xB2: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0xB3: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0xB4: {
        "command": "LDY",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xB5: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xB6: {
        "command": "LDX",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xB7: {
        "command": "LDA",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0xB8: {"command": "CLV", "length": 0, "m": False, "x": False, "mode": "_"},
    0xB9: {
        "command": "LDA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xBA: {"command": "TSX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xBB: {"command": "TYX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xBC: {
        "command": "LDY",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xBD: {
        "command": "LDA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xBE: {
        "command": "LDX",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xBF: {
        "command": "LDA",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xC0: {
        "command": "CPY",
        "length": 2,
        "m": False,
        "x": True,
        "mode": "#$_",
    },
    0xC1: {
        "command": "CMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0xC2: {
        "command": "REP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xC3: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0xC4: {
        "command": "CPY",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xC5: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xC6: {
        "command": "DEC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xC7: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0xC8: {"command": "INY", "length": 0, "m": False, "x": False, "mode": "_"},
    0xC9: {
        "command": "CMP",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0xCA: {"command": "DEX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xCB: {"command": "WAI", "length": 0, "m": False, "x": False, "mode": "_"},
    0xCC: {
        "command": "CPY",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xCD: {
        "command": "CMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xCE: {
        "command": "DEC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xCF: {
        "command": "CMP",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xD0: {
        "command": "BNE",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xD1: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0xD2: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0xD3: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0xD4: {
        "command": "PEI",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xD5: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xD6: {
        "command": "DEC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xD7: {
        "command": "CMP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0xD8: {"command": "CLD", "length": 0, "m": False, "x": False, "mode": "_"},
    0xD9: {
        "command": "CMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xDA: {"command": "PHX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xDB: {"command": "STP", "length": 0, "m": False, "x": False, "mode": "_"},
    0xDC: {
        "command": "JMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0xDD: {
        "command": "CMP",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xDE: {
        "command": "DEC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xDF: {
        "command": "CMP",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xE0: {
        "command": "CPX",
        "length": 2,
        "m": False,
        "x": True,
        "mode": "#$_",
    },
    0xE1: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0xE2: {
        "command": "SEP",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xE3: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,S",
    },
    0xE4: {
        "command": "CPX",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xE5: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xE6: {
        "command": "INC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xE7: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_]",
    },
    0xE8: {"command": "INX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xE9: {
        "command": "SBC",
        "length": 2,
        "m": True,
        "x": False,
        "mode": "#$_",
    },
    0xEA: {"command": "NOP", "length": 0, "m": False, "x": False, "mode": "_"},
    0xEB: {"command": "XBA", "length": 0, "m": False, "x": False, "mode": "_"},
    0xEC: {
        "command": "CPX",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xED: {
        "command": "SBC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xEE: {
        "command": "INC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xEF: {
        "command": "SBC",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_",
    },
    0xF0: {
        "command": "BEQ",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xF1: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_),Y",
    },
    0xF2: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_)",
    },
    0xF3: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "($_,S),Y",
    },
    0xF4: {
        "command": "PEA",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "#$_",
    },
    0xF5: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xF6: {
        "command": "INC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xF7: {
        "command": "SBC",
        "length": 1,
        "m": False,
        "x": False,
        "mode": "[$_],Y",
    },
    0xF8: {"command": "SED", "length": 0, "m": False, "x": False, "mode": "_"},
    0xF9: {
        "command": "SBC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,Y",
    },
    0xFA: {"command": "PLX", "length": 0, "m": False, "x": False, "mode": "_"},
    0xFB: {"command": "XCE", "length": 0, "m": False, "x": False, "mode": "_"},
    0xFC: {
        "command": "JSR",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "($_,X)",
    },
    0xFD: {
        "command": "SBC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xFE: {
        "command": "INC",
        "length": 2,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
    0xFF: {
        "command": "SBC",
        "length": 3,
        "m": False,
        "x": False,
        "mode": "$_,X",
    },
}
